/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    roles: Role;
    education: Education;
    media: Media;
    users: User;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr') | ('en' | 'fr')[];
  globals: {
    'site-content': SiteContent;
    'ui-text': UiText;
  };
  globalsSelect: {
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
    'ui-text': UiTextSelect<false> | UiTextSelect<true>;
  };
  locale: 'en' | 'fr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * URL-safe id, e.g. vscode-commit. Not translated.
   */
  key: string;
  order: number;
  name: string;
  what: string;
  /**
   * Tool names are the same in every language.
   */
  stack: string;
  year?: string | null;
  status: string;
  statusColor: 'var(--add)' | 'var(--accent2)' | 'var(--warn)' | 'var(--del)' | 'var(--dim)';
  detail?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        label: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        image?: (number | null) | Media;
        /**
         * Fallback path under /public for images not yet uploaded, e.g. /projects/britch/Screen1.png
         */
        path?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Described for screen readers, per language.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  key: string;
  order: number;
  /**
   * e.g. 2024 — now. Localised: 'now' translates.
   */
  when: string;
  what: string;
  where: string;
  detail?:
    | {
        /**
         * Left column, e.g. Scope, Led, Shipped.
         */
        label?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education".
 */
export interface Education {
  id: number;
  order: number;
  when: string;
  what: string;
  where: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Set during 2FA enrolment.
   */
  totpSecret?: string | null;
  /**
   * Require a one-time code at login.
   */
  totpEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  projects?: {
    /**
     * Allow clients to find projects.
     */
    find?: boolean | null;
    /**
     * Allow clients to create projects.
     */
    create?: boolean | null;
    /**
     * Allow clients to update projects.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete projects.
     */
    delete?: boolean | null;
  };
  roles?: {
    /**
     * Allow clients to find roles.
     */
    find?: boolean | null;
    /**
     * Allow clients to create roles.
     */
    create?: boolean | null;
    /**
     * Allow clients to update roles.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete roles.
     */
    delete?: boolean | null;
  };
  education?: {
    /**
     * Allow clients to find education.
     */
    find?: boolean | null;
    /**
     * Allow clients to create education.
     */
    create?: boolean | null;
    /**
     * Allow clients to update education.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete education.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
  };
  siteContent?: {
    /**
     * Allow clients to find site-content global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update site-content global.
     */
    update?: boolean | null;
  };
  uiText?: {
    /**
     * Allow clients to find ui-text global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update ui-text global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'education';
        value: number | Education;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  name?: T;
  what?: T;
  stack?: T;
  year?: T;
  status?: T;
  statusColor?: T;
  detail?:
    | T
    | {
        text?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        path?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  when?: T;
  what?: T;
  where?: T;
  detail?:
    | T
    | {
        label?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education_select".
 */
export interface EducationSelect<T extends boolean = true> {
  order?: T;
  when?: T;
  what?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  totpSecret?: T;
  totpEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  projects?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  roles?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  education?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  siteContent?:
    | T
    | {
        find?: T;
        update?: T;
      };
  uiText?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: number;
  name: string;
  tagline: string;
  location?: string | null;
  about: string;
  /**
   * First line of /now, also shown by the prompt.
   */
  headline: string;
  nowRows?:
    | {
        num: number;
        sign: ' ' | '+' | '-';
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  softSkills?:
    | {
        group: string;
        tint?: ('var(--accent)' | 'var(--accent2)' | 'var(--warn)' | 'var(--add)') | null;
        items?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  stack?:
    | {
        group: string;
        tint?: ('var(--accent)' | 'var(--accent2)' | 'var(--warn)' | 'var(--add)') | null;
        items?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  rates?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  contact?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  contactFooter?: string | null;
  resume?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-text".
 */
export interface UiText {
  id: number;
  promptPlaceholder: string;
  banner?: string | null;
  shortcuts?: string | null;
  modeHint?: string | null;
  intro?: {
    warm?: string | null;
    brief?: string | null;
    terse?: string | null;
  };
  introHints?:
    | {
        key?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  commands?:
    | {
        command: string;
        description: string;
        /**
         * Still runs, but absent from /help and autocomplete.
         */
        hidden?: boolean | null;
        id?: string | null;
      }[]
    | null;
  help?: {
    warm?: string | null;
    brief?: string | null;
    terse?: string | null;
  };
  projects?: {
    warm?: string | null;
    brief?: string | null;
    terse?: string | null;
  };
  skills?: {
    warm?: string | null;
    brief?: string | null;
    terse?: string | null;
  };
  stack?: {
    warm?: string | null;
    brief?: string | null;
    terse?: string | null;
  };
  rates?: {
    warm?: string | null;
    brief?: string | null;
    terse?: string | null;
  };
  contact?: {
    warm?: string | null;
    brief?: string | null;
    terse?: string | null;
  };
  now?: {
    warm?: string | null;
    brief?: string | null;
    terse?: string | null;
  };
  photos?: {
    warm?: string | null;
    brief?: string | null;
    terse?: string | null;
  };
  noMatch?: {
    warm?: string | null;
    brief?: string | null;
    terse?: string | null;
  };
  wizardSteps?:
    | {
        key: string;
        group: string;
        question: string;
        label?: string | null;
        options?:
          | {
              value: string;
              label: string;
              hint?: string | null;
              icon?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  wizardSent?: string | null;
  wizardErrors?:
    | {
        key: string;
        message: string;
        id?: string | null;
      }[]
    | null;
  themes?:
    | {
        value: string;
        label: string;
        hint?: string | null;
        id?: string | null;
      }[]
    | null;
  voices?:
    | {
        value: string;
        label: string;
        hint?: string | null;
        id?: string | null;
      }[]
    | null;
  keyHints?:
    | {
        key: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  location?: T;
  about?: T;
  headline?: T;
  nowRows?:
    | T
    | {
        num?: T;
        sign?: T;
        text?: T;
        id?: T;
      };
  softSkills?:
    | T
    | {
        group?: T;
        tint?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  stack?:
    | T
    | {
        group?: T;
        tint?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  rates?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  contactFooter?: T;
  resume?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-text_select".
 */
export interface UiTextSelect<T extends boolean = true> {
  promptPlaceholder?: T;
  banner?: T;
  shortcuts?: T;
  modeHint?: T;
  intro?:
    | T
    | {
        warm?: T;
        brief?: T;
        terse?: T;
      };
  introHints?:
    | T
    | {
        key?: T;
        text?: T;
        id?: T;
      };
  commands?:
    | T
    | {
        command?: T;
        description?: T;
        hidden?: T;
        id?: T;
      };
  help?:
    | T
    | {
        warm?: T;
        brief?: T;
        terse?: T;
      };
  projects?:
    | T
    | {
        warm?: T;
        brief?: T;
        terse?: T;
      };
  skills?:
    | T
    | {
        warm?: T;
        brief?: T;
        terse?: T;
      };
  stack?:
    | T
    | {
        warm?: T;
        brief?: T;
        terse?: T;
      };
  rates?:
    | T
    | {
        warm?: T;
        brief?: T;
        terse?: T;
      };
  contact?:
    | T
    | {
        warm?: T;
        brief?: T;
        terse?: T;
      };
  now?:
    | T
    | {
        warm?: T;
        brief?: T;
        terse?: T;
      };
  photos?:
    | T
    | {
        warm?: T;
        brief?: T;
        terse?: T;
      };
  noMatch?:
    | T
    | {
        warm?: T;
        brief?: T;
        terse?: T;
      };
  wizardSteps?:
    | T
    | {
        key?: T;
        group?: T;
        question?: T;
        label?: T;
        options?:
          | T
          | {
              value?: T;
              label?: T;
              hint?: T;
              icon?: T;
              id?: T;
            };
        id?: T;
      };
  wizardSent?: T;
  wizardErrors?:
    | T
    | {
        key?: T;
        message?: T;
        id?: T;
      };
  themes?:
    | T
    | {
        value?: T;
        label?: T;
        hint?: T;
        id?: T;
      };
  voices?:
    | T
    | {
        value?: T;
        label?: T;
        hint?: T;
        id?: T;
      };
  keyHints?:
    | T
    | {
        key?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}