import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ModuleHome } from "../modules/Home";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>RIOU Kevin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto bg-white my-24 py-24 px-36 rounded border-darky border-1 box-shadow flex flex-col justify-start items-center">
        <ModuleHome />
      </main>
    </>
  );
};

export default Home;
